#!/usr/bin/env python
import os
import sys
sys.path.append(os.path.abspath(''))
from config import *
try:
	REDUCED_DATA_EXTERNAL
except NameError: pass
else		: print "REDUCED_DATA_EXTERNAL is defined, please check what you realy want to do!"; exit()
try:
	CLUSTERS_DATA_EXTERNAL
except NameError: pass
else		: print "CLUSTERS_DATA_EXTERNAL is defined, please check what you realy want to do!"; exit()

from Main import reduc,cluster,plot
print "** REDUCTION **"
reduc()
print '\t[ok]\n'
print "** CLUSTERING **"
cluster()
print '\t[ok]\n'
print "** PLOTING **"
plot()
print '\t[ok]\n'

exit()
