#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.abspath(''))
from config_comparison import *
from plotting.plot_quality import plot_quality
if __name__=='__main__':
	print "** PLOTTING COMPARISON **\n"
	os.system('mkdir -p plots/')
	plot_quality(QUALITY_METHODS,'plots/quality'+PLOT_QUA_EXT)
	print '\t* QUALITY PLOT generated at ->','plots/quality'+PLOT_QUA_EXT
	print '\t[ok]\n'
	exit()
