#!/usr/bin/env python
import sys
import os
sys.path.append(os.path.abspath(''))
from config_comparisson import *
from ploting.plot_quality import plot_quality
if __name__=='__main__':
	print "** PLOTING COMPARISSON **\n"
	plot_quality(QUALITY_METHODS,'plots/quality'+PLOT_QUA_EXT)
	print '\t[ok]\n'
	exit()
