#!/usr/bin/env python
from config import *
try:
	CLUSTERING_DATA
except NameError: pass
else		: print "CLUSTERING_DATA is defined, please check what you realy want to do!"; exit()

print "REDUCTION"
from CODE.Main import reduc
reduc()
print "CLUSTERING"
from CODE.Main import plot
plot()
exit()
