#!/bin/bash

#PARAMS='0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9'
PARAMS='2 3 4 5 6 7 8  9'
#PARS='2 3 4 5 6 7 8 9'
PARS='2 3 4 5 6 7 8 9'

for COMP in $PARS
do

for PARAM in $PARAMS
do
CONF="
#####################################################################################
'''
Original data:
	Used for the reduction,
	not needed if doing clusreing only
'''
ORG_DATA			= '/home/emille/Documents/github/mlsnespectra/MLSNeSpectra/data_all_types/derivatives.dat'

#####################################################################################
'''
REDUCTION METHOD
	possibilities:
		-pca
	The aditional parameters must be added with the same name
	as in the original function plus the prefix REDUCTION_METHOD'_'.
	Example:
		if REDUCTION_METHOD is 'pca', the parameter
		n_components must be declared as 
			pca_n_components= ...
		if REDUCTION_METHOD is 'empca', the parameter
		error_file can be declared as 
			empca_errors_file= ...
                in order to run with weights=1/errors^2. Its default value is
                None, so empca runs without weights
'''
REDUCTION_METHOD	= 'pca'
pca_n_components = "$COMP"

#####################################################################################
'''
CLUSTERING METHOD
	possibilities:
		-MeanShift
		-KMeans
		-AffinityPropagation
		-AgglomerativeClustering
		-DBSCAN

	The aditional parameters must be added with the same name
	as in the original function plus the prefix CLUSTERING_METHOD'_'
	Example:
		if CLUSTERING_METHOD is 'MeanShift', the parameter 
		quantile must be declared as 
			MeanShift_quantile= ...

'''
CLUSTERING_METHOD	= 'KMeans'
KMeans_n_clusters	= "$PARAM"

#####################################################################################
'''
CLUSTERING OUTPUT EXTENSIONS
	extension of output plots produced by pylab
'''
PLOT_EXT	= '.png'
PLOT_SPEC_EXT = '.pdf'
#####################################################################################
'''
QUALITY TEST METHODS
	put one or more (as a vector) quality checks for clustering. possibilities are:
		-silhouette_index
		-Dunn_index
		-DavisBouldin_index
		-vrc

'''
QUALITY_METHODS=['silhouette_index','Dunn_index','DavisBouldin_index','vrc']

#####################################################################################
'''
CLUSTERING INPUT DATA
	add this ONLY if you want to use a external data source for the clustering,
	if you want to use the data from the pipeline leave it commented.
	Be aware that this data will also go into the plotting.
'''

REDUCED_DATA_EXTERNAL =    'out//out_120,100,90,50,30,20,"$COMP",20,30,50,90,100,120_seed1_dl.dat'
MASK_DATA   = '../../../../data_all_types/labels.dat'
SPECTRAL_DATA_EXTERNAL      = '../../../../data_all_types/fluxes.dat'

#####################################################################################
'''
PLOTTING INPUT DATA
	add this ONLY if you want to use a external data source of the clusters for the plotting,
	if you want to use the data from the pipeline leave it commented.
	You can also add an external file with different label to set different colors
	to the reduced data. The default color scheme is according to each parent cluster.
'''
#CLUSTERS_DATA_EXTERNAL		= '../empca_trained_coeff/coefficients.dat'
#LABELS_DATA_EXTERNAL		= '../empca_trained_coeff/coefficients.dat'
"

echo "$CONF" > config.py

CLUSTERING
QUALITY
PLOT
PLOT_SPECS -a

mv  info/quality.info info/quality_"$COMP"PC_"$PARAM"groups.info
mv plots/plot_EXT_KMeans.png plots/plot_EXT_KMeans_"$COMP"PC_"$PARAM"groups.png
mv plots/plot_EXT_KMeans_specs.pdf plots/plot_EXT_KMeans_specs_"$COMP"PC_"$PARAM"groups.pdf
mv red_data/reduced_data_EXT.dat red_data/reduced_data_EXT_"$COMP"PC_"$PARAM"groups.dat
mv cl_data/clustering_KMeans.dat cl_data/clustering_KMeans_"$COMP"PC_"$PARAM"groups.dat
mv cl_data/clustering_KMeans_label.dat cl_data/clustering_KMeans_label_"$COMP"PC_"$PARAM"groups.dat

done


done
